-- AlterTable
ALTER TABLE "Casernes" ALTER COLUMN "lat" SET DATA TYPE TEXT,
ALTER COLUMN "long" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Communes" ALTER COLUMN "lat" SET DATA TYPE TEXT,
ALTER COLUMN "long" SET DATA TYPE TEXT;
